### ISSUE TITLE
postgres error

### ISSUE THREAD

**Issue by paulvanbladel** [assafg/osiris#5]
Nice Project.
Unfortunately I run into problems when using postgres (didn't try other dbs).

Can you please first check if my calling sequence is ok.
I wrote following integrationt test:
```
const test = require('tape')
const PostgresDB = require('../lib/database/postgresdb')
const EventSource = require('../lib/EventSource')

test('smoke test', t => {
  const db = new PostgresDB({
    table: 'trial',
    connectionString: 'postgresql:/xxxx:xxxx@xxx:5432/xxx'
  })

  const es = new EventSource(db, 'trial')
  let event = { context: 'mycontext', street: 'fifth av' }
  es.onEvent(event)
  event = { context: 'mycontext', city: 'new york' }
  es.onEvent(event)
  es.getState('mycontext').then(d => {
    console.log('result', d)
  })
  t.end()
})
```
This is the result
```
 tape -r ./tests/integration.spec.js
TAP version 13
# smoke 2
result { seq: 36,
  data: { context: 'mycontext', city: 'new york', street: 'fifth av' } }
(node:22104) UnhandledPromiseRejectionWarning: error: null value in column "context" violates not-null constraint
    at Connection.parseE (E:\GITHUB3RD\osiris\node_modules\pg\lib\connection.js:554:11)
    at Connection.parseMessage (E:\GITHUB3RD\osiris\node_modules\pg\lib\connection.js:379:19)
    at Socket.<anonymous> (E:\GITHUB3RD\osiris\node_modules\pg\lib\connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
(node:22104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by assafg** [comment]
Thanks for the kind feedback. Fixed this in https://github.com/assafg/osiris/commit/0ff3bc53c52e2ceeda536bcf23e245fc8b82a472

One thing you should notice in your example is that the `es.onEvent(event)` is asyncrounous. To properly test it you should use Promise.all(...) to resolve all the es events and only then get the sate. You can see a new example (based on your code) at https://github.com/assafg/osiris/blob/master/examples/local-postgressdb/index.js
